version: '3.8'

services:
  # Database services
  postgres:
    image: postgres:15-alpine
    container_name: fastenmind_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: fastenmind
      POSTGRES_PASSWORD: fastenmind123
      POSTGRES_DB: fastenmind_db
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - fastenmind_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastenmind"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fastenmind_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fastenmind_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastenmind_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=fastenmind
      - DB_PASSWORD=fastenmind123
      - DB_NAME=fastenmind_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - fastenmind_network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fastenmind_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
    networks:
      - fastenmind_network

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fastenmind_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fastenmind.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - fastenmind_network

  # N8N (optional)
  n8n:
    image: n8nio/n8n:latest
    container_name: fastenmind_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - fastenmind_network

volumes:
  postgres_data:
  redis_data:
  n8n_data:

networks:
  fastenmind_network:
    driver: bridge